from from_root import from_root

TRANSPILER_DATABASE_NAME = "TRANSPILER_DATABASE"
FULL_DIRECTORY_WITH_DB_NAME = str(from_root(f"database/metadata/{TRANSPILER_DATABASE_NAME}.db"))
HISTORY_TABLE_NAME = "TRANSPILER_HISTORY"